### ISSUE TITLE
Name collision: `Sql.Datepart()` method shadows the `Datepart` enum under `using static SqlArtisan.Sql;`

### ISSUE THREAD

**Issue by h-tacayama** [h-tacayama/SqlArtisan#99]
## Summary

The public factory method `Sql.Datepart(...)` and the public enum `Datepart` share the same simple name. When a user follows the README-recommended `using static SqlArtisan.Sql;` and writes any `Datepart.X` enum member in **expression position**, the C# compiler binds `Datepart` to the imported **method** rather than the **enum type**, producing a build error:

```
error CS0119: 'Sql.Datepart(Datepart, object)' is a method, which is not valid in the given context
```

This is a **pre-existing** issue (it already affects `Extract(Datepart.Year, ...)`), surfaced while doing real-engine verification for #86. It is not caused by #86, but #86's new `DateAdd` / `DateDiff` / `DateTrunc` functions all take a `Datepart` argument, so users will hit it more often.

## Reproduction

A normal user project — own namespace, both usings at the same scope level, exactly as the README suggests (§ "add a static using for `SqlArtisan.Sql`"):

```csharp
using SqlArtisan;
using static SqlArtisan.Sql;

namespace MyApp;

internal sealed class Program
{
    private static void Main()
    {
        // All three fail with CS0119 on `Datepart.X`:
        var a = Select(Extract(Datepart.Year, CurrentTimestamp)).Build(Dbms.PostgreSql);  // pre-existing
        var b = Select(Datepart(Datepart.Year, CurrentTimestamp)).Build(Dbms.SqlServer);
        var c = Select(DateAdd(Datepart.Month, 1, CurrentTimestamp)).Build(Dbms.SqlServer);
    }
}
```

## Why the test suite doesn't catch it

`tests/SqlArtisan.Tests/**` lives under `namespace SqlArtisan.Tests`. Because `Datepart` (the enum) is then resolvable via the **enclosing** `SqlArtisan` namespace — which outranks `using static` imports in name resolution — the enum wins and the tests compile. Flat user code outside the `SqlArtisan` namespace has no such protection.

A regression test should be added in a **non-`SqlArtisan` namespace** to reproduce real-world usage.

## Workarounds (all verified to compile against a live build)

- Fully qualify the enum: `SqlArtisan.Datepart.Month`
- Alias the enum: `using Dp = SqlArtisan.Datepart;` then `Dp.Month`
- Don't `using static`; call explicitly: `Sql.DateAdd(Datepart.Month, ...)`

## Possible resolutions (for discussion)

1. **Rename the `Datepart()` factory method** so it no longer collides with the enum (breaking; the method emits SQL Server `DATEPART`, so a more specific/dialect-flavoured name is an option).
2. **Rename the enum** (breaking; affects `Extract`, `Datepart`, and the #86 functions).
3. **Document the workaround** in the README near the `Datepart` usage (non-breaking, lowest cost).

Renaming is a breaking public-API change, so it likely belongs to a major/beta version bump. Flagging for a decision.

## Acceptance criteria

- A regression test outside the `SqlArtisan` namespace that reproduces the collision.
- A chosen resolution applied (rename or documented workaround), with README/CHANGELOG updated accordingly.
